version: '3.9'

secrets:
  config:
    file: /root/.priority2030

services:
  app:
    build: .
    restart: always
    secrets:
      - config
    environment:
      CONFIG_FILE: /run/secrets/config
    volumes:
      - app:/app

volumes:
  app:
